name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::511097557993:role/GitHubActionsRole
  AWS_REGION: us-east-1
  APP_NAME: hello-fargate

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: terraform
        run: |
          terraform destroy -auto-approve -input=false -var "aws_region=${{ env.AWS_REGION }}" -var "app_name=${{ env.APP_NAME }}"
